### ISSUE TITLE
Update requirement to ginga v2.6.1 or v2.6.2 ?

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/glue-ginga#16]
Although there is no strong urgency to do so, I wonder whether we should update the required version of ginga in the plugin package.  It seems to me that at the very least it would be better to specify a version in the new versioning scheme, which is similar to other packages now.

The latest released Ginga is 2.6.2

**Comment by pllim** [comment]
Currently in `setup.py`:
```
      install_requires=['glueviz>=0.9.0',
                        'ginga>=2.5.20161113213300']
```

IMHO, as long as this is still backward compatible, there is no need to update the requirements, as installer will automatically pick the latest release anyway (unless there is a prior installation). Although, since this package is not widely used yet, this also does not hurt. So, I am neutral on this.

**Comment by ejeschke** [comment]
It's backward compatible, but I think it might make sense to align the version with one of the github releases.  Maybe 2.6.1 then...?

**Comment by pllim** [comment]
I don't have a preference. :smile:

**Comment by astrofrog** [comment]
Aligning with 2.6.1 is fine by me

**Comment by ejeschke** [comment]
I've updated the requirement to 2.6.1 in commit 041bc9cbe398af72b2a7adb8b9056d9b5f56aa2b
