### ISSUE TITLE
Apply astropy package template?

### ISSUE THREAD

**Issue by pllim** [ejeschke/glue-ginga#7]
What do you think, @astrofrog ?

**Comment by astrofrog** [comment]
I've avoided using astropy-helpers in glue because I don't want to make it look like an astronomy-specific package, and I don't use things like the configuration framework, and it's pure Python, so no compilation - so there's not a huge benefit to using the astropy package template. I'm not really sure we really need it here either.

**Comment by pllim** [comment]
I mainly want to take advantage of the dev version tagging here.

**Comment by ejeschke** [comment]
I think we can probably just add the bits the tag the dev version with the git commit.  I agree that it's probably not necessary for the package as it stands now.
